//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFGiacoReservas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Artista
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Artista()
        {
            this.Tb_EventoArtista = new HashSet<Tb_EventoArtista>();
        }
    
        public int artista_id { get; set; }
        public string nombre_artista { get; set; }
        public decimal costo_hora { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<int> IdGenero { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string ActualizadoPor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_EventoArtista> Tb_EventoArtista { get; set; }
        public virtual Tb_Genero Tb_Genero { get; set; }
    }
}
